### ISSUE TITLE
Windows exe gives a very grey window, nothing else

### ISSUE THREAD

**Issue by TheShaman** [balkaneum/McAfeeMiner#3]
Just downloaded the Windows exe from the release page, when I start it I only get a grey window, nothing is happening at all. 

The regular Safex One Click miner works fine on the same system (Windows 10 64bit, Ryzen 5 1600, AMD RX580, but I think this miner is CPU only anyways). 

Any undocumented dependencies on Windoze? 
Or just a faulty build?

**Edit:** started it from command line just to see if there are any useful error messages, but the only thing it does is open the plain dark grey window, and print "pre-main prep time: 1 ms"

And that was all it ever did. No lambo anytime soon. :rofl:

**Comment by TheShaman** [comment]
No sweat. :)

Just wanted to let you know. 

While we are at it: I tried building it on Solus Linux and failed miserably (and I am no Linux noob). 

A one-click miner targets desktop "users", it would be great if after the Windows exe is usable you guys could release a Linux build as a distro-independent appimage or flatpak or snap to make it easy for new users. 

The mining market is highly competitive, new, less technically inclined users bring growth, and even the old nerds have become tired of 5000 super-specific and unfulfillable dependencies to build something that then maybe earns 15 Cent per day... LOL

**Comment by atanmarko** [comment]
Fix released
